const projects = {
  'color':      { url: 'digital/color',      title: 'Color',      year: '2025', cat: 'Digital',  sub: 'Stock project',   client: '<a href="https://treedeo.com" target="_blank" style="color:inherit;text-decoration:underline;">Treedeo</a>',   desc: '',
    blocks: [
      { type: 'full',     imgs: ['img/Color_Site/COLOR_18.jpg'] },
      { type: 'carousel', imgs: ['img/Color_Site/COLOR_19.jpg','img/Color_Site/COLOR_14.jpg','img/Color_Site/COLOR_20.jpg','img/Color_Site/COLOR_03.jpg'] },
      { type: 'grid2x2',  imgs: ['img/Color_Site/COLOR_09.jpg','img/Color_Site/COLOR_05.jpg','img/Color_Site/COLOR_08.jpg','img/Color_Site/COLOR_06.jpg'] },
      { type: 'full',     imgs: ['img/Color_Site/COLOR_13.jpg'] },
      { type: '3col',     imgs: ['img/Color_Site/COLOR_10.jpg','img/Color_Site/COLOR_11.jpg','img/Color_Site/COLOR_12.jpg'] },
      { type: '2col',     imgs: ['img/Color_Site/COLOR_17.jpg','img/Color_Site/COLOR_18.jpg'] },
      { type: 'full',     imgs: ['img/Color_Site/COLOR_07.jpg'] },
    ]},
  'glass':      { url: 'digital/glass',      title: 'Glass',      year: '2024', cat: 'Digital',  sub: 'Personal project', client: '<a href="https://treedeo.com" target="_blank" style="color:inherit;text-decoration:underline;">Treedeo</a>',   desc: '',
    blocks: [
      { type: 'full',     imgs: ['img/GLASS_site/GLASS_01.jpg'] },
      { type: 'carousel', imgs: ['img/GLASS_site/GLASS_02.jpg','img/GLASS_site/GLASS_03.jpg','img/GLASS_site/GLASS_04.jpg','img/GLASS_site/GLASS_05.jpg','img/GLASS_site/GLASS_07.jpg'] },
      { type: 'grid2x2',  imgs: ['img/GLASS_site/GLASS_08.jpg','img/GLASS_site/GLASS_09.jpg','img/GLASS_site/GLASS_10.jpg','img/GLASS_site/GLASS_11.jpg'] },
      { type: 'full',     imgs: ['img/GLASS_site/GLASS_12.jpg'] },
      { type: '3col',     imgs: ['img/GLASS_site/GLASS_13.jpg','img/GLASS_site/GLASS_14.jpg','img/GLASS_site/GLASS_15.jpg'] },
      { type: '2col',     imgs: ['img/GLASS_site/GLASS_16.jpg','img/GLASS_site/GLASS_17.jpg'] },
      { type: 'full',     imgs: ['img/GLASS_site/GLASS_18.jpg'] },
      { type: 'carousel', imgs: ['img/GLASS_site/GLASS_19.jpg','img/GLASS_site/GLASS_20.jpg','img/GLASS_site/GLASS_21.jpg'] },
      { type: '2col',     imgs: ['img/GLASS_site/GLASS_22.jpg','img/GLASS_site/GLASS_23.jpg'] },
      { type: 'full',     imgs: ['img/GLASS_site/GLASS_20.jpg'] },
    ]},
  'tex':        { url: 'digital/tex',        title: 'Tex',        year: '2023', cat: 'Digital',  sub: 'Personal project', client: '<a href="https://treedeo.com" target="_blank" style="color:inherit;text-decoration:underline;">Treedeo</a>',   desc: '',
    blocks: [
      { type: 'full',  imgs: ['img/Tex_Site/Tex_04.jpg'] },
      { type: '2col',  imgs: ['img/Tex_Site/Tex_02.jpg','img/Tex_Site/Tex_03.jpg'] },
      { type: '2col',  imgs: ['img/Tex_Site/Tex_05.jpg','img/Tex_Site/Tex_06.jpg'] },
      { type: 'full',  imgs: ['img/Tex_Site/Tex_07.jpg'] },
    ]},
  'title':      { url: 'digital/title',      title: 'Title',      year: '2023', cat: 'Digital',  sub: 'Personal project', client: '<a href="https://treedeo.com" target="_blank" style="color:inherit;text-decoration:underline;">Treedeo</a>',   desc: '',
    blocks: [
      { type: 'full',     imgs: ['img/TITLE_site/TITLE_13.jpg'] },
      { type: 'carousel', imgs: ['img/TITLE_site/TITLE_19.jpg','img/TITLE_site/TITLE_20.jpg','img/TITLE_site/TITLE_17.jpg','img/TITLE_site/TITLE_21.jpg','img/TITLE_site/TITLE_06.jpg'] },
      { type: 'grid2x2',  imgs: ['img/TITLE_site/TITLE_07.jpg','img/TITLE_site/TITLE_08.jpg','img/TITLE_site/TITLE_09.jpg','img/TITLE_site/TITLE_10.jpg'] },
      { type: 'full',     imgs: ['img/TITLE_site/TITLE_22.jpg'] },
      { type: '2col',     imgs: ['img/TITLE_site/TITLE_12.jpg','img/TITLE_site/TITLE_01.jpg'] },
      { type: 'full',     imgs: ['img/TITLE_site/TITLE_14.jpg'] },
    ]},
  'waves':      { url: 'digital/waves',      title: 'Waves',      year: '2023', cat: 'Digital',  sub: 'Personal project', client: '<a href="https://treedeo.com" target="_blank" style="color:inherit;text-decoration:underline;">Treedeo</a>',   desc: '',
    blocks: [
      { type: 'full',  imgs: ['img/WAVES_site/WAVES_01.jpg'] },
      { type: '2col',  imgs: ['img/WAVES_site/WAVES_06.jpg','img/WAVES_site/WAVES_03.jpg'] },
      { type: 'full',  imgs: ['img/WAVES_site/WAVES_09.jpg'] },
      { type: '2col',  imgs: ['img/WAVES_site/WAVES_07.jpg','img/WAVES_site/WAVES_08.jpg'] },
    ]},
  'rainbow':    { url: 'digital/rainbow',    title: 'Rainbow',    year: '2022', cat: 'Digital',  sub: 'Personal project', client: '<a href="https://treedeo.com" target="_blank" style="color:inherit;text-decoration:underline;">Treedeo</a>',   desc: '',
    blocks: [
      { type: 'full',     imgs: ['img/Rainbow_site/Rainbow_01.jpg'] },
      { type: 'carousel', imgs: ['img/Rainbow_site/Rainbow_25.jpg','img/Rainbow_site/Rainbow_26.jpg','img/Rainbow_site/Rainbow_27.jpg','img/Rainbow_site/Rainbow_28.jpg'] },
      { type: 'grid2x2',  imgs: ['img/Rainbow_site/Rainbow_07.jpg','img/Rainbow_site/Rainbow_08.jpg','img/Rainbow_site/Rainbow_09.jpg','img/Rainbow_site/Rainbow_10.jpg'] },
      { type: '2col',     imgs: ['img/Rainbow_site/Rainbow_05.jpg','img/Rainbow_site/Rainbow_06.jpg'] },
      { type: 'full',     imgs: ['img/Rainbow_site/Rainbow_02.jpg'] },
    ]},
  'wood':       { url: 'digital/wood',       title: 'Wood',       year: '2022', cat: 'Digital',  sub: 'Personal project', client: '<a href="https://treedeo.com" target="_blank" style="color:inherit;text-decoration:underline;">Treedeo</a>',   desc: '',
    blocks: [
      { type: 'full',     imgs: ['img/Wood_site/WOOD_01.jpg'] },
      { type: '2col',     imgs: ['img/Wood_site/WOOD_06.jpg','img/Wood_site/WOOD_05.jpg'] },
      { type: 'carousel', imgs: ['img/Wood_site/WOOD_04.jpg','img/Wood_site/WOOD_02.jpg','img/Wood_site/WOOD_03.jpg','img/Wood_site/WOOD_10.jpg'] },
      { type: 'full',     imgs: ['img/Wood_site/WOOD_09.jpg'] },
      { type: '2col',     imgs: ['img/Wood_site/WOOD_07.jpg','img/Wood_site/WOOD_08.jpg'] },
      { type: 'carousel', imgs: ['img/Wood_site/WOOD_13.jpg','img/Wood_site/WOOD_15.jpg','img/Wood_site/WOOD_16.jpg','img/Wood_site/WOOD_18.jpg','img/Wood_site/WOOD_19.jpg'] },
      { type: 'full',     imgs: ['img/Wood_site/WOOD_21.jpg'] },
    ]},
  'land-cruiser': { url: 'mapping/land-cruiser', title: 'Land cruiser', year: '2023', cat: 'Mapping',  sub: 'Commercial',       client: '<a href="https://www.dreamlaser.ru/" target="_blank" style="color:inherit;text-decoration:underline;">DreamLaser</a>', desc: 'The task was to create a full CG video featuring a Land Cruiser 300 in various extreme conditions. I had a scene in the desert.',
    blocks: [
      { type: 'full',  imgs: ['img/Land_cruiser_site/sc_06_Sanddunes_stillframe.jpg'] },
      { type: 'video', imgs: ['img/Land_cruiser_site/sc_06_sanddunes.mp4'] },
      { type: 'video', imgs: ['img/Land_cruiser_site/sc_06_sanddunes_Led_Smoke.mp4'] },
      { type: 'video', imgs: ['img/Land_cruiser_site/sc_06_sanddunes_Led_GEO.mp4'] },
      { type: 'video',  imgs: ['img/Land_cruiser_site/sc_06_sanddunes_Cinema4D.mp4'] },
    ]},
  'vivienne-sabo': { url: 'mapping/vivienne-sabo', title: 'Vivienne Sabó', year: '2023', cat: 'Mapping',  sub: 'Commercial',       client: '<a href="https://www.dreamlaser.ru/" target="_blank" style="color:inherit;text-decoration:underline;">DreamLaser</a>', desc: '', 
    blocks: [
      { type: '2col',      imgs: ['img/VIVIENNE_SABO_site/VSabo_03.jpg','img/VIVIENNE_SABO_site/VSabo_01.jpg'] },
      { type: '2col',      imgs: ['img/VIVIENNE_SABO_site/VSabo_02.jpg','img/VIVIENNE_SABO_site/VSabo_04.jpg'] },
      { type: '2col',      imgs: ['img/VIVIENNE_SABO_site/VSabo_05.jpg','img/VIVIENNE_SABO_site/VSabo_06.jpg'] },
      { type: '2col',      imgs: ['img/VIVIENNE_SABO_site/VSabo_07.jpg','img/VIVIENNE_SABO_site/VSabo_08.jpg'] },
      { type: '2col',      imgs: ['img/VIVIENNE_SABO_site/VSabo_09.jpg','img/VIVIENNE_SABO_site/VSabo_10.jpg'] },
      { type: 'video2col', imgs: ['img/VIVIENNE_SABO_site/VSabo_video_03.mp4','img/VIVIENNE_SABO_site/VSabo_video_02.mp4'] },
      { type: 'video',     imgs: ['img/VIVIENNE_SABO_site/VSabo_video_FULL.mp4'] },
    ]},
  'mapping': { url: 'mapping/projects', title: 'Mapping', year: '2023', cat: 'Mapping',  sub: 'Commercial',       client: '<a href="https://www.dreamlaser.ru/" target="_blank" style="color:inherit;text-decoration:underline;">DreamLaser</a>', desc: '', 
    blocks: [
      { type: 'imgvideo',  imgs: ['img/NEVSKIY_site/NEVSKIY_Wood_01.jpg','img/NEVSKIY_site/NEVSKIY_Wood_video.mp4'] },
      { type: 'imgvideo',  imgs: ['img/NEVSKIY_site/NEVSKIY_Metal_02.jpg','img/NEVSKIY_site/NEVSKIY_Metal_video.mp4'] },
      { type: 'full',      imgs: ['img/PLANETARY_site/PLANETARY_01.jpg'] },
      { type: 'video',     imgs: ['img/PLANETARY_site/PLANETARY_01_video.mp4'] },
      { type: '2col',      imgs: ['img/VDNH_site/sc_05_Flowers.jpg','img/VDNH_site/sc_04_Map.jpg'] },
      { type: 'video',     imgs: ['img/VDNH_site/sc_05_Flowers_video.mp4'] },
      { type: 'full',      imgs: ['img/TAVRIDA_sita/TAVRIDA_01.jpg'] },
      { type: 'full',      imgs: ['img/TAVRIDA_sita/TAVRIDA_02.jpg'] },
      { type: 'video',     imgs: ['img/TAVRIDA_sita/TAVRIDA_video.mp4'] },
    ] }
   
};