const PROJECTS = [
  {
    id: 'color',
    url: '/digital/color',
    title: 'COLOR',
    year: '2025',
    tags: ['Digital', 'Stock project', 'Client: Treedeo'],
    description: 'Project description. Tell about the task, process and result. What was interesting about this work, which tools you used, who you collaborated with.',
    blocks: [
      { type: 'full', src: '/img/Color_Site/COLOR_01.jpg' },
      { type: 'full', src: '/img/Color_Site/COLOR_02.jpg' },
      { type: 'full', src: '/img/Color_Site/COLOR_03.jpg' },
      { type: '2col', srcs: ['/img/Color_Site/COLOR_04.jpg', '/img/Color_Site/COLOR_05.jpg'] },
      { type: 'full', src: '/img/Color_Site/COLOR_06.jpg' },
      { type: 'full', src: '/img/Color_Site/COLOR_07.jpg' },
      { type: '2col', srcs: ['/img/Color_Site/COLOR_08.jpg', '/img/Color_Site/COLOR_09.jpg'] },
      { type: 'full', src: '/img/Color_Site/COLOR_10.jpg' },
      { type: 'full', src: '/img/Color_Site/COLOR_11.jpg' },
      { type: '2col', srcs: ['/img/Color_Site/COLOR_12.jpg', '/img/Color_Site/COLOR_13.jpg'] },
      { type: 'full', src: '/img/Color_Site/COLOR_14.jpg' },
      { type: '2col', srcs: ['/img/Color_Site/COLOR_15.jpg', '/img/Color_Site/COLOR_16.jpg'] },
      { type: 'full', src: '/img/Color_Site/COLOR_17.jpg' },
      { type: 'full', src: '/img/Color_Site/COLOR_18.jpg' },
      { type: 'full', src: '/img/Color_Site/COLOR_19.jpg' },
      { type: 'full', src: '/img/Color_Site/COLOR_20.jpg' },
      { type: '2col', srcs: ['/img/Color_Site/COLOR_21.jpg', '/img/Color_Site/COLOR_22.jpg'] },
      { type: 'full', src: '/img/Color_Site/COLOR_23.jpg' },
      { type: 'full', src: '/img/Color_Site/COLOR_24.jpg' },
    ]
  },
  {
    id: 'waves',
    url: '/digital/waves',
    title: 'WAVES',
    year: '2023',
    tags: ['Digital', 'Stock project', 'Client: Treedeo'],
    description: 'Project description. Tell about the task, process and result. What was interesting about this work, which tools you used, who you collaborated with.',
    blocks: [
      { type: 'full', src: '/img/WAVES_site/WAVES_01.jpg' },
      { type: 'full', src: '/img/WAVES_site/WAVES_02.jpg' },
      { type: 'full', src: '/img/WAVES_site/WAVES_03.jpg' },
      { type: 'full', src: '/img/WAVES_site/WAVES_04.jpg' },
      { type: 'full', src: '/img/WAVES_site/WAVES_05.jpg' },
      { type: 'full', src: '/img/WAVES_site/WAVES_06.jpg' },
      { type: 'full', src: '/img/WAVES_site/WAVES_07.jpg' },
      { type: 'full', src: '/img/WAVES_site/WAVES_08.jpg' },
      { type: 'full', src: '/img/WAVES_site/WAVES_09.jpg' },
    ]
  },
  {
    id: 'glass',
    url: '/digital/glass',
    title: 'GLASS',
    year: '2024',
    tags: ['Digital', 'Stock project', 'Client: Treedeo'],
    description: 'Project description. Tell about the task, process and result. What was interesting about this work, which tools you used, who you collaborated with.',
    blocks: [
      { type: 'full', src: '/img/GLASS_site/GLASS_01.jpg' },
      { type: 'full', src: '/img/GLASS_site/GLASS_02.jpg' },
      { type: 'full', src: '/img/GLASS_site/GLASS_03.jpg' },
      { type: 'full', src: '/img/GLASS_site/GLASS_04.jpg' },
      { type: 'full', src: '/img/GLASS_site/GLASS_05.jpg' },
      { type: 'full', src: '/img/GLASS_site/GLASS_06.jpg' },
      { type: 'full', src: '/img/GLASS_site/GLASS_07.jpg' },
      { type: 'full', src: '/img/GLASS_site/GLASS_08.jpg' },
      { type: 'full', src: '/img/GLASS_site/GLASS_09.jpg' },
      { type: 'full', src: '/img/GLASS_site/GLASS_10.jpg' },
      { type: 'full', src: '/img/GLASS_site/GLASS_11.jpg' },
      { type: 'full', src: '/img/GLASS_site/GLASS_12.jpg' },
      { type: 'full', src: '/img/GLASS_site/GLASS_13.jpg' },
      { type: 'full', src: '/img/GLASS_site/GLASS_14.jpg' },
      { type: 'full', src: '/img/GLASS_site/GLASS_15.jpg' },
      { type: 'full', src: '/img/GLASS_site/GLASS_16.jpg' },
      { type: 'full', src: '/img/GLASS_site/GLASS_17.jpg' },
      { type: 'full', src: '/img/GLASS_site/GLASS_18.jpg' },
      { type: 'full', src: '/img/GLASS_site/GLASS_19.jpg' },
      { type: 'full', src: '/img/GLASS_site/GLASS_20.jpg' },
    ]
  },
  {
    id: 'title',
    url: '/digital/title',
    title: 'TITLE',
    year: '2023',
    tags: ['Digital', 'Personal project', 'Client: Treedeo'],
    description: 'Project description. Tell about the task, process and result. What was interesting about this work, which tools you used, who you collaborated with.',
    blocks: [
      { type: 'full', src: '/img/TITLE_site/TITLE_01.jpg' },
      { type: 'full', src: '/img/TITLE_site/TITLE_02.jpg' },
      { type: 'full', src: '/img/TITLE_site/TITLE_03.jpg' },
      { type: 'full', src: '/img/TITLE_site/TITLE_04.jpg' },
      { type: 'full', src: '/img/TITLE_site/TITLE_05.jpg' },
      { type: 'full', src: '/img/TITLE_site/TITLE_06.jpg' },
      { type: 'full', src: '/img/TITLE_site/TITLE_07.jpg' },
      { type: 'full', src: '/img/TITLE_site/TITLE_08.jpg' },
      { type: 'full', src: '/img/TITLE_site/TITLE_09.jpg' },
      { type: 'full', src: '/img/TITLE_site/TITLE_10.jpg' },
      { type: 'full', src: '/img/TITLE_site/TITLE_11.jpg' },
      { type: 'full', src: '/img/TITLE_site/TITLE_12.jpg' },
      { type: 'full', src: '/img/TITLE_site/TITLE_13.jpg' },
      { type: 'full', src: '/img/TITLE_site/TITLE_14.jpg' },
      { type: 'full', src: '/img/TITLE_site/TITLE_15.jpg' },
      { type: 'full', src: '/img/TITLE_site/TITLE_16.jpg' },
      { type: 'full', src: '/img/TITLE_site/TITLE_17.jpg' },
      { type: 'full', src: '/img/TITLE_site/TITLE_18.jpg' },
      { type: 'full', src: '/img/TITLE_site/TITLE_19.jpg' },
      { type: 'full', src: '/img/TITLE_site/TITLE_20.jpg' },
      { type: 'full', src: '/img/TITLE_site/TITLE_21.jpg' },
    ]
  },
  {
    id: 'wood',
    url: '/digital/wood',
    title: 'WOOD',
    year: '2022',
    tags: ['Digital', 'Stock project', 'Client: Treedeo'],
    description: 'Project description. Tell about the task, process and result. What was interesting about this work, which tools you used, who you collaborated with.',
    blocks: [
      { type: 'full', src: '/img/Wood_site/WOOD_01.jpg' },
      { type: 'full', src: '/img/Wood_site/WOOD_02.jpg' },
      { type: 'full', src: '/img/Wood_site/WOOD_03.jpg' },
      { type: 'full', src: '/img/Wood_site/WOOD_04.jpg' },
      { type: 'full', src: '/img/Wood_site/WOOD_05.jpg' },
      { type: 'full', src: '/img/Wood_site/WOOD_06.jpg' },
      { type: 'full', src: '/img/Wood_site/WOOD_07.jpg' },
      { type: 'full', src: '/img/Wood_site/WOOD_08.jpg' },
      { type: 'full', src: '/img/Wood_site/WOOD_09.jpg' },
      { type: 'full', src: '/img/Wood_site/WOOD_10.jpg' },
      { type: 'full', src: '/img/Wood_site/WOOD_13.jpg' },
      { type: 'full', src: '/img/Wood_site/WOOD_15.jpg' },
      { type: 'full', src: '/img/Wood_site/WOOD_16.jpg' },
      { type: 'full', src: '/img/Wood_site/WOOD_18.jpg' },
      { type: 'full', src: '/img/Wood_site/WOOD_19.jpg' },
      { type: 'full', src: '/img/Wood_site/WOOD_21.jpg' },
    ]
  },
  {
    id: 'rainbow',
    url: '/digital/rainbow',
    title: 'RAINBOW',
    year: '2022',
    tags: ['Digital', 'Stock project', 'Client: Treedeo'],
    description: 'Project description. Tell about the task, process and result. What was interesting about this work, which tools you used, who you collaborated with.',
    blocks: [
      { type: 'full', src: '/img/Rainbow_site/Rainbow_01.jpg' },
      { type: 'full', src: '/img/Rainbow_site/Rainbow_02.jpg' },
      { type: 'full', src: '/img/Rainbow_site/Rainbow_03.jpg' },
      { type: 'full', src: '/img/Rainbow_site/Rainbow_04.jpg' },
      { type: 'full', src: '/img/Rainbow_site/Rainbow_05.jpg' },
      { type: 'full', src: '/img/Rainbow_site/Rainbow_06.jpg' },
      { type: 'full', src: '/img/Rainbow_site/Rainbow_07.jpg' },
      { type: 'full', src: '/img/Rainbow_site/Rainbow_08.jpg' },
      { type: 'full', src: '/img/Rainbow_site/Rainbow_09.jpg' },
      { type: 'full', src: '/img/Rainbow_site/Rainbow_10.jpg' },
      { type: 'full', src: '/img/Rainbow_site/Rainbow_27.jpg' },
    ]
  },
  {
    id: 'tex',
    url: '/digital/tex',
    title: 'TEX',
    year: '2023',
    tags: ['Digital', 'Stock project', 'Client: Treedeo'],
    description: 'Project description. Tell about the task, process and result. What was interesting about this work, which tools you used, who you collaborated with.',
    blocks: [
      { type: 'full', src: '/img/Tex_Site/Tex_01.jpg' },
      { type: 'full', src: '/img/Tex_Site/Tex_02.jpg' },
      { type: 'full', src: '/img/Tex_Site/Tex_03.jpg' },
      { type: 'full', src: '/img/Tex_Site/Tex_04.jpg' },
      { type: 'full', src: '/img/Tex_Site/Tex_05.jpg' },
      { type: 'full', src: '/img/Tex_Site/Tex_06.jpg' },
      { type: 'full', src: '/img/Tex_Site/Tex_07.jpg' },
      { type: 'full', src: '/img/Tex_Site/Tex_08.jpg' },
    ]
  },
  {
    id: 'mapping-01',
    url: '/mapping/mapping-01',
    title: 'MAPPING 01',
    year: '2024',
    tags: ['Mapping', 'DreamLaser'],
    description: 'Project description here.',
    blocks: [
      { type: 'full', src: '/img/Land_cruiser_site/sc_06_Sanddunes_stillframe.jpg' },
      { type: 'full', src: '/img/Land_cruiser_site/sc_06_Sanddunes_Led_GEO.gif' },
      { type: 'full', src: '/img/Land_cruiser_site/sc_06_sanddunes_Led_Smoke.gif' },
      { type: '2col', srcs: ['/img/Land_cruiser_site/sc_06_sanddunes_setup.jpg', '/img/Land_cruiser_site/sc_06_sanddunes_setup_2.jpg'] },
      { type: 'full', src: '/img/Land_cruiser_site/2023_02_06_19_38_15.gif' },
    ]
  },
  {
    id: 'mapping-02',
    url: '/mapping/mapping-02',
    title: 'MAPPING 02',
    year: '2023',
    tags: ['Mapping', 'DreamLaser'],
    description: 'Project description here.',
    blocks: []
  },
  {
    id: 'mapping-03',
    url: '/mapping/mapping-03',
    title: 'MAPPING 03',
    year: '2023',
    tags: ['Mapping', 'DreamLaser'],
    description: 'Project description here.',
    blocks: []
  },
  {
    id: 'mapping-04',
    url: '/mapping/mapping-04',
    title: 'MAPPING 04',
    year: '2022',
    tags: ['Mapping', 'DreamLaser'],
    description: 'Project description here.',
    blocks: []
  },
  {
    id: 'mapping-05',
    url: '/mapping/mapping-05',
    title: 'MAPPING 05',
    year: '2022',
    tags: ['Mapping', 'DreamLaser'],
    description: 'Project description here.',
    blocks: []
  },
];
